services:

  odoo:
    image: odoo:17.0
    container_name: odoo
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8070:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=${ODOO_HOST}
      - USER=${ODOO_USER}
      - PASSWORD=${ODOO_PASSWORD}
    command: odoo -d ${ODOO_USER} --db_user=${ODOO_USER} --db_password=${ODOO_PASSWORD} -i base

  db:
    image: postgres:15.0
    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${ODOO_USER}
      - POSTGRES_PASSWORD=${ODOO_PASSWORD}
      - POSTGRES_USER=${ODOO_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  odoo-data:
  db-data:


